name: github_action

on:
  push:
    branches: [ "main" ]

jobs:

  app-test:

    runs-on: ubuntu-latest

    steps:
    
    - name: Clone my repo
    - uses: actions/checkout@v1
    
    - name: List current folder
      run : ls -la

#    - name: ESLint Reporter
      # You may pin to the exact commit or the version.
      # uses: rahmanrafi/eslint-reporter-action@42d01025c94d5dc8c53aa610ff88fd893c6c00b4
#      uses: rahmanrafi/eslint-reporter-action@v3
#      with:
        # ESLint results JSON
#        json: 
        # Title to use for report'
#        title: # optional, default is ESLint Report
      
#  app-build:

#    runs-on: ubuntu-latest
#    needs: [app-test]
    
#    steps:
    
#    - name: Build Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)     
      
