name: github_action

on:
  push:
    branches: [ "main" ]

jobs:

  action-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone my repo
      uses: actions/checkout@v1
    
    - name: List current folder
      run : ls -la
      
    - name: Install ESLint
      run : |
       npm install eslint@8.10.0
       npm install @microsoft/eslint-formatter-sarif@2.1.7

    - name: Run ESLint
      run: npx eslint .
      continue-on-error: true
  
      
#  action-build:
#    runs-on: ubuntu-latest
#    needs: [action-test]
#    steps:
#    - name: Build Docker image
#      run: docker build .
