name: github_action

on:
  push:
    branches: [ "main" ]

jobs:

  app-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone my repo
      uses: actions/checkout@v1
    
    - name: List current folder
      run : ls -la
      
#  app-build:
#    runs-on: ubuntu-latest
#    needs: [app-test]
#    steps:
#    - name: Build Docker image
#      run: docker build .
